#!/usr/bin/python
# -*- coding: latin-1 -*-
import os, sys
import os.path
import time
import datetime
import busio
import digitalio
import board
import adafruit_mcp3xxx.mcp3008 as MCP
from adafruit_mcp3xxx.analog_in import AnalogIn
# create the spi bus
spi = busio.SPI(clock=board.SCK, MISO=board.MISO, MOSI=board.MOSI)
# create the cs (chip select)
cs = digitalio.DigitalInOut(board.D5)
# create the mcp object
mcp = MCP.MCP3008(spi, cs)
# create an analog input channel on pin (Pn)
chan0 = AnalogIn(mcp, MCP.P0)
chan1 = AnalogIn(mcp, MCP.P1)
chan2 = AnalogIn(mcp, MCP.P2)
#Wert des Identifikations Wiederstandes
r1 = 460
fileNumber = 0


print('Reading MCP3008 values, press Ctrl-C to quit...')
def filecreator():

    while (os.path.exists(datetime.datetime.now().strftime("%y""%m""%d")+"-"+str(fileNumber)+".txt") == True):
        fileNumber += 1
        print(fileNumber)
    file = open(datetime.datetime.now().strftime("%y""%m""%d")+"-"+str(fileNumber+".txt"), "a")
    file.write("Neue Messung:"+datetime.datetime.now().strftime("%X")+ "\n")
    print("file created")


def identifier():
    ohm = r1*((chan0.voltage)/(3.3-(chan0.voltage)))
    print(str(ohm))
    #Identifier logic noch schreiben wen wiederstand so und so viel ohm = Metall
    print("identified cartridge")

def adcfilewriter():
    valuetotal0 = 0
    countSoll = 20
    countIst = 0
    value1 = chan1.voltage
    value2 = chan2.voltage

    while countSoll != countIst:
        valuetotal1 = value1+valuetotal1
        valuetotal2 = value2 + valuetotal2
        time.sleep(0.1)
        countIst +=1

    total1 = valuetotal1/countSoll
    total1 = "{:.5f}".format(total1)
    total2 = valuetotal2/countSoll
    total2 = "{:.5f}".format(total2)

    file = open(datetime.datetime.now().strftime("%y""%m""%d") + "-" + str(fileNumber)+".txt", "a")
    file.write("/t" + total1 + "/t" + total2 + "\n")
    print(total1)


filecreator()
identifier()
while True :
    adcfilewriter()
    #time.sleep(1)
